### ISSUE TITLE
PHP Setup not working without MySQL

### ISSUE THREAD

**Issue by chrootLogin** [team-rawbot/rawbot-virtualization#12]
playbook.yml:
```
---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the rawbot-virtualization README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  sudo: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }

    ## Database, choose either mysql or postgres, some subsequent roles will be configured
    ## depending on your choice here.
    # - { role: mysql }
    # - { role: postgresql }

    ## Scripting / Language support
    # - { role: php-fpm }       # PHP using Nginx and PHP-FPM
    - { role: php-apache }    # PHP using Apache and mod-php
    # - { role: django }        # Django framework

    ## Webserver, choose one of those only if you have not choosed a scripting language
    ## above
    # - { role: nginx }          # Nginx for basic HTML website
    # - { role: apache }         # Apache for basic HTML website

    ## Install compass in the box
    # - { role: compass }

    ## Install Solr in the box
    # - { role: solr }

    ## Install Composer in the box
    - { role: composer }

    ## You can also creates your own role, just add a directory under the 'virtualization'
    ## folder and refer to it like for other roles :
    # - { role: my_own_role }

# If needed, you can specify your own tasks, here is an example :
#  tasks:
#    - name: install project dev tools
#      shell: cd {{ root_directory }} && composer.phar --quiet install
#    - name: Copy application config file
#      shell: cp -f {{ root_directory }}/config/server_config.php.vagrant {{ root_directory }}/config/server_config.php
#    - name: Provision the database
#      shell: cd {{ root_directory }} && ./console mysql:reset
```
parameters.yml:
```
---
# Name of your project, will also be the vagrant box name
project_name: "liip-support-page"

# Main hostname through which the vagrant box will be accessible
hostname: "support.dev"
# Alternative hostnames through which you want to access the vagrant box
hostnames: []

# The box IP, this must be unique across all your virtualized projects to
# avoid collisions. WARNING, this parameter will not guarantee that your box
# will be accessible at this IP depending on your network configuration or
# provider choice.
box_ip: "10.10.10.10"

# Name of the database to create for your project if you include the
# MySQL or PostgreSQL role
database_name: "rawbot"

# Root directory of your project for the webserver and other purposes
root_directory: "/vagrant/"

# Do we activate SSL ?
# ssl: yes

# For a PHP project, you might want to set the following
# Default reporting level of PHP errors
# php_error_reporting: "E_ALL & ~E_NOTICE"

# For a Django project, you might want to set the following
# django_pip_requirements: "dev"
# django_version: "1.6"
```

Console output:
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'wheezy64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'wheezy64' (v0) for provider: virtualbox
    default: Downloading: http://vagrantbox-public.liip.ch/liip-wheezy64.box
==> default: Successfully added box 'wheezy64' (v0) for 'virtualbox'!
==> default: Importing base box 'wheezy64'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: supportliipch_default_1435312391430_91813
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.2.16
    default: VirtualBox Version: 4.3
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
==> default: Mounting NFS shared folders...
==> default: Updating /etc/hosts file on active guest machines...
==> default: Updating /etc/hosts file on host machine (password may be required)...
==> default: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=no -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/simu/Arbeit/Projekte/support.liip.ch/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/Users/simu/Arbeit/Projekte/support.liip.ch/.vagrant/provisioners/ansible/inventory virtualization/playbook.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [base | ensure python-apt is installed] ********************************* 
ok: [default]

TASK: [base | ensure apt database is up-to-date] ****************************** 
ok: [default]

TASK: [base | set en_US.UTF-8 as generated locale] **************************** 
changed: [default]

TASK: [base | set en_US.UTF-8 as default locale] ****************************** 
changed: [default]

TASK: [base | ensure members of sudo can sudo password-less] ****************** 
changed: [default]

TASK: [base | ensure base packages are installed] ***************************** 
changed: [default] => (item=locales,procps,command-not-found,bash-completion,zsh,bzip2,unzip,git,vim,ack-grep,build-essential,wget,openssh-server,sudo,imagemagick,iputils-ping,ncurses-term,python-pycurl)

TASK: [base | install shell config] ******************************************* 
changed: [default] => (item=aliases)
changed: [default] => (item=bashrc)
changed: [default] => (item=zshrc)
changed: [default] => (item=liquidpromptrc)
changed: [default] => (item=gitconfig)
changed: [default] => (item=gitglobalignore)
changed: [default] => (item=ackrc)
changed: [default] => (item=vimrc)

TASK: [base | install liquidprompt] ******************************************* 
changed: [default]

TASK: [base | use liquidprompt as prompt] ************************************* 
changed: [default]

TASK: [base | cd to /vagrant when sshing] ************************************* 
changed: [default]

TASK: [base | add vagrant user to www-data group] ***************************** 
changed: [default]

TASK: [base | get local git username] ***************************************** 
changed: [default -> 127.0.0.1]

TASK: [base | get local git email] ******************************************** 
changed: [default -> 127.0.0.1]

TASK: [base | set box git username and email] ********************************* 
changed: [default]

TASK: [base | disallow setting of LANG and LOCALE] **************************** 
changed: [default]

NOTIFIED: [base | restart ssh] ************************************************ 
changed: [default]

TASK: [php | install PHP5 packages] ******************************************* 
changed: [default] => (item=php5-xcache,php5-xdebug,php5-curl,php5-cli,php5-intl,php5-gd,php5-imagick)

TASK: [php | install mysql database driver] *********************************** 
fatal: [default] => error while evaluating conditional: database_type == 'mysql'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/simu/playbook.retry

default                    : ok=18   changed=15   unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
